### ISSUE TITLE
Log in using google account fialed in version 0.7.1

### ISSUE THREAD

**Issue by rachmanabdau-getgo** [ComposeFlow/composeflow-issues#1]
Hi thanks for inviting me to your closed alpha testing. I am using mac book and chrome browser. I tried to login in ComposeFlow Version 0.7.1 but it was failed. This is the error i got

<img width="1470" alt="Screenshot 2024-12-19 at 08 35 50" src="https://github.com/user-attachments/assets/02413d59-5ab6-4f39-a9f0-b1f2a7affbfb" />

**Comment by thagikura** [comment]
Hi, thanks for reporting the issue.

Is it possible to know your environment? Such as 

OS:
Version:

Thanks!

**Comment by rachmanabdau-getgo** [comment]
I am using mac book

OS: Mac OS
Version: Sequoia 15.1

**Comment by thagikura** [comment]
Is it possible to change your default browser to another browser? So that the callback is received with another browser?


If it still persist with another browser, I think changing the callback url to 127.0.0.1 instead of localhost might avoid the issue.
In that case, I appreciate if I send you a patched version of the app to try if changing the callback url helps.
If that sounds comfortable with you, please reach out to .. , then I'll send you a patched version of the app. (and make a patched release if that resolves the issue)

**Comment by rachmanabdau-getgo** [comment]
I still got the same result, itried it on different browsers, on ssfari and firefox. I even chenged the call back url from localhost to 127.0.0.1 it didn't work.

Here is the screenshot from firefox:
<img width="1470" alt="Screenshot 2024-12-19 at 17 01 20" src="https://github.com/user-attachments/assets/731818fd-ae8c-4c86-99e2-476ece55d3d7" />

I think i will reach out to you via e-mail and get the patched version instead. Meanwhile i will close the issue.
